@endpoint = https://x4drv33jmd.execute-api.us-east-1.amazonaws.com/prod/hello

GET {{endpoint}}/hello
###
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location":"London",
    "name":"Best Location"
}
###